#!/bin/sh
### BEGIN INIT INFO
# Provides:           slpbridge
# Required-Start:     $syslog $network
# Required-Stop:      $syslog $network
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  SLP Bridge
# Description:
#  A super-simple SLP Bridge daemon
### END INIT INFO

set -e

BASE=slpbridge
DESC="SLP Bridge"

DAEMON=/usr/local/sbin/$BASE
LOGFILE=/var/log/$BASE.log
PIDFILE=/var/run/$BASE.pid

# Get lsb functions
. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
        . /etc/default/$BASE
fi

fail_unless_root() {
        if [ "$(id -u)" != '0' ]; then
                log_failure_msg "$DESC must be run as root"
                exit 1
        fi
}

case "$1" in
	start)
		fail_unless_root 
		log_begin_msg "Starting $DESC: $BASE"
		start-stop-daemon --start --oknodo --background \
			--no-close \
			--startas "$DAEMON" \
			--pidfile "$PIDFILE" \
			--make-pidfile \
			-- \
			$SOURCE_IFACE $TARGET_IFACE \
		>> $LOGFILE 2>&1
		log_end_msg $?
	;;

	stop)
		fail_unless_root
		log_begin_msg "Stopping $DESC: $BASE"
		start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
		log_end_msg $?
	;;

	restart)
		fail_unless_root
		pid=`cat $PIDFILE 2>/dev/null`
		[ -n "$pid" ] && ps -p $pid > /dev/null 2>&1 && $0 stop
		$0 start
	;;

	status)
		status_of_proc -p "$PIDFILE" "$DAEMON" "$DESC"
	;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
